document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\' xml:lang=\'en\' lang=\'en\' > ");
document.writeln("<head><title>愚仁杰的GitHub博客</title>");
document.writeln(" <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div id=\'main\'>");
document.writeln(" <div id=\'info\'>");
document.writeln("	 <div id=\'headimage\'>");
document.writeln("		<span></span>");
document.writeln("	 </div>");
document.writeln("	 <dl class=\'person-info\'>");
document.writeln("            <dd class=\'person-nick-name\'>");
document.writeln("            			<span>愚仁杰</span>            </dd>");
document.writeln("            <dd class=\'person-detail\'> ");
document.writeln("            		程序猿<span>|</span>广东省");
document.writeln("			</dd>");
document.writeln("			<dd class=\'person-detail\'> ");
document.writeln("            		篮球<span>&bull;</span>足球<span>&bull;</span>音乐");
document.writeln("			</dd>");
document.writeln("            <dd class=\'person-sign\'>Think once, run everywhere.</dd>");
document.writeln("      </dl>");
document.writeln(" </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");